### ISSUE TITLE
Can't reach you by mail

### ISSUE THREAD

**Issue by EmBitz** [tgree/psdb#72]
Hi Terry,

I wrote you back but the email can't be delivered.

Error:

Message delivery to 'tgxxxxxx@phxxxxxxors.com' delayed SMTP module(domain phasesensors.com) reports:
 connection with smtp.secureserver.net is broken

-Gerard

**Comment by tgree** [comment]
Hi Gerard,

Sorry that I missed your message here!  I'm not sure what the problem with my phasesensors.com email was, but perhaps you could try emailing me at my gmail address instead:

terrygreeniaus@gmail.com

Thanks so much!

TG
